#!/usr/bin/env ruby
# frozen_string_literal: true
#
# SBOM (Software Bill of Materials) signing use case — threshold-sign
# SPDX / CycloneDX SBOM documents so downstream consumers can verify
# the manifest was produced by an authorized quorum of stakeholders
# (release engineer + security officer + auditor, for example).
#
# Why threshold signing for SBOMs?
#
#   - **Supply-chain integrity**: a single compromised SBOM-signing
#     key lets an attacker ship a tampered manifest alongside a
#     backdoored artifact. Threshold signing forces a quorum.
#   - **Compliance**: SLSA Build Level 3+ requires verified build
#     provenance. Threshold signatures satisfy the "no single party
#     can attest alone" requirement by construction.
#   - **Cross-org trust**: SBOMs verified under a joint public key
#     are trusted across organizational boundaries (e.g. a
#     regulator verifies a vendor's SBOM without needing direct
#     access to the vendor's internal PKI).
#
# Run: `bundle exec ruby examples/sbom_signing.rb`

require "base64"
require "digest"
require "json"
require "confium"

# Synthetic SPDX-2.3 SBOM. Real SBOMs are generated by syft / cyclonedx-bom
# / spdx-tools; the wire format is JSON or tag-value.
sbom = {
  spdxVersion: "SPDX-2.3",
  dataLicense: "CC0-1.0",
  SPDXID: "SPDXRef-DOCUMENT",
  name: "imaginary-app-1.0.0",
  documentNamespace: "https://example.com/spdx/imaginary-app-1.0.0",
  creationInfo: {
    created: "2026-07-31T00:00:00Z",
    creators: ["Tool: confium-sbom-signer", "Organization: ExampleCorp"],
  },
  packages: [
    {
      SPDXID: "SPDXRef-Package-app",
      name: "imaginary-app",
      versionInfo: "1.0.0",
      downloadLocation: "https://registry.example.com/app:1.0.0",
      filesAnalyzed: false,
      licenseConcluded: "Apache-2.0",
      licenseDeclared: "Apache-2.0",
      checksums: [{ algorithm: "SHA256", checksumValue: "abc123..." }],
    },
    {
      SPDXID: "SPDXRef-Package-dep-openssl",
      name: "openssl",
      versionInfo: "3.0.12",
      downloadLocation: "https://openssl.org/source/openssl-3.0.12.tar.gz",
      filesAnalyzed: false,
      licenseConcluded: "Apache-2.0",
    },
  ],
}
sbom_json = JSON.generate(sbom)

puts "== Setup: load SBOM-signing quorum's threshold key =="
kg = Confium::TC::Cmp20.keygen(3, 5)
puts "  SBOM quorum joint public key: 0x#{kg["public_key"].unpack1("H*")[0, 24]}..."
puts "  5 shares held by: release_engineer, security_officer, build_engineer,"
puts "                  auditor, compliance_lead (3-of-5 required)"

puts
puts "== Build engineer assembles SBOM =="
puts "  SBOM: #{sbom[:name]} (#{sbom[:packages].length} packages)"

puts
puts "== 3-of-5 quorum threshold-signs the SBOM =="
three_shares = kg["shares"].first(3)
puts "  participating: build_engineer, security_officer, auditor"
sig = Confium::TC::Cmp20.sign(three_shares, 3, sbom_json)
puts "  SBOM signature: 0x#{sig.unpack1("H*")[0, 24]}... (#{sig.bytesize} bytes)"

puts
puts "== Wrap signature + SBOM together (sigstore-style) =="
signed_sbom = {
  sbom: Base64.strict_encode64(sbom_json),
  signature: {
    algorithm: "ECDSA-P256",
    threshold_scheme: "CMP20-ECDSA-P256",
    quorum: "3-of-5",
    value: Base64.strict_encode64(sig),
    public_key: Base64.strict_encode64(kg["public_key"]),
  },
}
File.write("/tmp/imaginary-app-1.0.0.spdx.json", sbom_json)
File.write("/tmp/imaginary-app-1.0.0.spdx.sig.json", JSON.generate(signed_sbom))
puts "  wrote: /tmp/imaginary-app-1.0.0.spdx.json"
puts "         /tmp/imaginary-app-1.0.0.spdx.sig.json"

puts
puts "== Downstream consumer verifies =="
loaded = JSON.parse(File.read("/tmp/imaginary-app-1.0.0.spdx.sig.json"))
loaded_sbom = Base64.strict_decode64(loaded["sbom"])
loaded_sig = Base64.strict_decode64(loaded["signature"]["value"])
loaded_pk = Base64.strict_decode64(loaded["signature"]["public_key"])

require "openssl"
asn1 = OpenSSL::ASN1::Sequence([
  OpenSSL::ASN1::Sequence([
    OpenSSL::ASN1::ObjectId("id-ecPublicKey"),
    OpenSSL::ASN1::ObjectId("prime256v1"),
  ]),
  OpenSSL::ASN1::BitString(loaded_pk),
])
pkey = OpenSSL::PKey::EC.new(asn1.to_der)
r = OpenSSL::BN.new(loaded_sig[0, 32], 2)
s = OpenSSL::BN.new(loaded_sig[32, 32], 2)
der = OpenSSL::ASN1::Sequence([OpenSSL::ASN1::Integer(r), OpenSSL::ASN1::Integer(s)]).to_der
digest = Digest::SHA256.digest(loaded_sbom)

if pkey.dsa_verify_asn1(digest, der)
  puts "  ✓ SBOM verified — signed by 3-of-5 publisher quorum"
  parsed_sbom = JSON.parse(loaded_sbom)
  puts "  Package count: #{parsed_sbom["packages"].length}"
  puts "  SPDX version:  #{parsed_sbom["spdxVersion"]}"
else
  abort "  ✗ SBOM signature FAILED"
end

puts
puts "== Anchor SBOM + signature to transparency log =="
tree = Confium::Transparency::MerkleTree.new
tree.append(Digest::SHA256.digest(sbom_json + sig))
puts "  transparency root: 0x#{tree.root.unpack1("H*")[0, 24]}..."
puts
puts "Done. The SBOM is signed by a 3-of-5 quorum, distributed alongside"
puts "the artifact, verifiable by any downstream consumer, and anchored"
puts "to a transparency log for non-repudiation of supply-chain history."
