name: test-and-release

on:
  push:
    branches: [ main ]
    tags:     [ 'v*' ]
  pull_request:
  workflow_dispatch:

env:
  INSTALL_DIR: ${{ github.workspace }}/installs

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        default: true
        profile: minimal

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

      # Install os-specific build dependencies and
      # set up os-specific environment variables environment
    - name: install os-specific build deps and environment (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get -y install libbotan-2-dev cmake make g++
    - name: install os-specific build deps and environment (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install botan
    - name: install os-specific build deps and environment (Windows)
      if: runner.os == 'Windows'
      shell: bash
      run: |
        set -eux
        pacman --noconfirm -S --needed pactoys
        pacboy sync --noconfirm libbotan:p
        echo "CMAKE_GENERATOR=MSYS Makefiles" >> $GITHUB_ENV
        echo "$INSTALL_DIR/lib" >> $GITHUB_PATH
        rustup target add --toolchain nightly-x86_64-pc-windows-msvc x86_64-pc-windows-gnu

    - name: Checkout confium core
      uses: actions/checkout@v3
      with:
        repository: confium/confium
        path: confium
        fetch-depth: 1
        submodules: recursive

    - name: Confium build
      shell: bash
      run: |
        mkdir confium-build
        cd confium-build
        cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DBUILD_TESTING=off ../confium
        cmake --build . --target install

    - name: Checkout Botan plugin
      uses: actions/checkout@v3
      with:
        repository: confium/confium-plugin-botan
        path: confium-plugin-botan
        fetch-depth: 1

    - name: Plugin build
      shell: bash
      run: |
        mkdir confium-plugin-botan-build
        cd confium-plugin-botan-build
        cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR ../confium-plugin-botan
        cmake --build . --target install

    - name: Bundle
      run: bundle

    - name: Test
      shell: bash
      run: |
        export LD_LIBRARY_PATH=$INSTALL_DIR/lib
        export DYLD_LIBRARY_PATH=$INSTALL_DIR/lib
        export RUBY_DLL_PATH=$INSTALL_DIR/lib
        bundle exec rspec

  release:
    name: Release gem
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3

      - uses: cadwallion/publish-rubygems-action@master
        env:
          RUBYGEMS_API_KEY: ${{secrets.CONFIUM_CI_RUBYGEMS_API_KEY}}
